version: '3.8'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "${ACC_DB_PORT}:${ACC_DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${ACC_POSTGRES_PASSWORD}
      - POSTGRES_USER=${ACC_POSTGRES_USER}
    image: postgres:15.1-bullseye